### PR TITLE
Everything works good, please check one more time, or screen the error, and put the comment section 

### PR DESCRIPTION
**Pull request by Islomtursunboyev**

### CODE REVIEW

**Comment by bahtibek-an** [comment]
What's your name Islom Tursunboyev or Zahro Abdurashidov?
Only one person can submit from one repository or account.

**Review by bahtibek-an — CHANGES_REQUESTED** [review]
What's your name Islom Tursunboyev or Zahro Abdurashidov?
Only one person can submit from one repository or account.

**Comment by Islomtursunboyev** [comment]
We are doing in a group

**Comment by Islomtursunboyev** [comment]
Why, in qwasar we can do in a group, and we do it

**Comment by bahtibek-an** [comment]
Here in github you mustn't do in a group, you have to do separately

**Pull request closed without merging**
