### PR TITLE
Frontend_My_Dropbox_project_by_Jenis_Bozdakhov

### PR DESCRIPTION
**Pull request by Bozdakhov**
My Dropbox project created in react.js, firebase.

### CODE REVIEW

**Comment by Bozdakhov** [comment]
Frontend-My-Dropbox project is ready for review.

**Review by bahtibek-an — APPROVED** [review]
Well done. All features implemented.
Good luck with your next projects

**Comment by Takeda04** [comment]
Astrum - Your project's review has been rejected!
Project - my_dropbox
Status - plagiarism 
You should come to the mentor's room within 5 days to complete the essential task to prove that you don't plagiarize, or it will be counted as plagiarism

**Review by Takeda04 — CHANGES_REQUESTED** [review]
Astrum - Your project's review has been rejected!
Project - my_dropbox
Status - plagiarism 
You should come to the mentor's room within 5 days to complete the essential task to prove that you don't plagiarize, or it will be counted as plagiarism

**Pull request closed without merging**
